using UnityEngine;
using System.Collections;

public class PlayerScript : MonoBehaviour {

    public Vector2 speed = new Vector2(50, 50);

    private Vector2 movement;
	
	void Update () 
    {
        float inputX = Input.GetAxis("Horizontal");
        float inputY = Input.GetAxis("Vertical");

        movement = new Vector2(
          speed.x * inputX,
          speed.y * inputY);

        // 5 - Shooting
        bool shoot = Input.GetButtonDown("Fire1");
        shoot |= Input.GetButtonDown("Fire2");
        // Careful: For Mac users, ctrl + arrow is a bad idea

        if (shoot)
        {
            WeaponScript weapon = GetComponent<WeaponScript>();
            if (weapon != null)
            {
                // false because the player is not an enemy
                weapon.Attack(false);
            }
        }
	}

    void FixedUpdate()
    {
        rigidbody2D.velocity = movement;
    }

		void OnCollisionEnter2D(Collision2D collision)
		{
			bool damagePlayer = false;

			// Collision with enemy
			EnemyScript enemy = collision.gameObject.GetComponent<EnemyScript>();
			if (enemy != null)
			{
				// Kill the enemy
				HealthScript enemyHealth = enemy.GetComponent<HealthScript>();
				if (enemyHealth != null) enemyHealth.Damage(enemyHealth.hp);

				damagePlayer = true;
			}

			// Damage the player
			if (damagePlayer)
			{
				HealthScript playerHealth = this.GetComponent<HealthScript>();
				if (playerHealth != null) playerHealth.Damage(1);
			}
		}
}
